spring:
  config:
    import:
      - classpath:/backend-secret/application-local.yml
      - classpath:/backend-secret/application-dev.yml
      - classpath:/backend-secret/application-test.yml
  profiles:
    default: dev
    active: dev

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**

logging:
  level:
    root: INFO
    com.core.backend: DEBUG