version: '3'
services:
  fintech-dev:
    container_name: fintech-dev
    image: woohahalife/fintech-backend
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/backend-admin/logs:/app/logs
    networks:
      - backend-network

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - /home/backend-admin/app/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend-network

networks:
  backend-network:
    external: true