name: Backend Server Deploy to MS Azure VM and Docker

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches    
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-    

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build --parallel
        shell: bash

      - name: Run Tests with Gradle
        run: ./gradlew test
        shell: bash

      - name: Docker Build & Push to Hub
        run: |
          docker login -u woohahalife -p ${{ secrets.DOCKER_HUB_TOKEN }}  
          docker build -t woohahalife/fintech-backend -f ./.docker/Dockerfile .  
          docker push woohahalife/fintech-backend  

      - name: Send docker-compose.yml to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./.docker/docker-compose.yml"
          target: "/home/backend-admin"

      - name: Send deploy.sh to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./scripts"
          target: "/home/backend-admin"

      - name: Connect to Azure VM & Execute Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo cp /home/${{ secrets.AZURE_USERNAME }}/.docker/docker-compose.yml /home/${{ secrets.AZURE_USERNAME }}  
            sudo cp /home/${{ secrets.AZURE_USERNAME }}/scripts/deploy.sh /home/${{ secrets.AZURE_USERNAME }}  
            docker pull woohahalife/fintech-backend  
            sudo chmod 777 ./deploy.sh  
            ./deploy.sh  
            docker image prune -f
